// <auto-generated />
using CardinalWebApi.Models;
using CardinalWebApiLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CardinalWebApi.Migrations
{
    [DbContext(typeof(CardinalDbContext))]
    partial class CardinalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardinalWebApi.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PinCode");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CardinalWebApi.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<decimal>("Price");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CardinalWebApi.Models.Tab", b =>
                {
                    b.Property<Guid>("TabId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardToken");

                    b.Property<int>("CurrentState");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("TimestampClosed");

                    b.Property<DateTime>("TimestampFinalized");

                    b.Property<DateTime>("TimestampOpened");

                    b.HasKey("TabId");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("CardinalWebApi.Models.TabHistory", b =>
                {
                    b.Property<Guid>("TabHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionText");

                    b.Property<Guid?>("EmployeeId");

                    b.Property<Guid?>("TabId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("TabHistoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TabId");

                    b.ToTable("TabHistories");
                });

            modelBuilder.Entity("CardinalWebApi.Models.TabLineItem", b =>
                {
                    b.Property<Guid>("TabId");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ItemId");

                    b.Property<int>("Quantity");

                    b.HasKey("TabId", "Order");

                    b.HasIndex("ItemId");

                    b.ToTable("TabLineItems");
                });

            modelBuilder.Entity("CardinalWebApi.Models.TabHistory", b =>
                {
                    b.HasOne("CardinalWebApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("CardinalWebApi.Models.Tab", "Tab")
                        .WithMany()
                        .HasForeignKey("TabId");
                });

            modelBuilder.Entity("CardinalWebApi.Models.TabLineItem", b =>
                {
                    b.HasOne("CardinalWebApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("CardinalWebApi.Models.Tab", "Tab")
                        .WithMany("Items")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
